inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/MultilineIfModifier:
  Exclude:
    - 'db/**/*'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
Style/FetchEnvVar:
  Exclude:
    - 'bin/bundle'
Style/RedundantConstantBase:
  Exclude:
    - 'config/environments/production.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
Lint/MissingSuper:
  Enabled: false
